### ISSUE TITLE
SRIMeanBaselineTemplate is not a valid Template

### ISSUE THREAD

**Issue by proska** [usc-isi-i2/dsbox-ta2#105]
The template SRIMeanBaselineTemplate does not have a valid taskType, taskSubtype, and inputType field in the template.

**Comment by liangmuxin** [comment]
The initial idea of that template is to take every dataset in and generate a baseline depends on mean value. So it will cover every tasktype, subtype and inputtype field. In function get_template in library.py, I append it in list before we do searching so that every run of dataset will have a meanbaseline prediction.

**Comment by proska** [comment]
Oh, I see. So you want a template that is supposed to be compatible with all the datasets?

**Comment by liangmuxin** [comment]
True.
