### ISSUE TITLE
Error in processing location attributes

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/dsbox-ta2#120]
See /dsbox_efs/runs/seed-2018-07-26-02:04/LL1_336_MS_Geolife_transport_mode_prediction/supporting_files/logs/out.txt

Should not use SKImputer?

**Comment by proska** [comment]
@kyao The problem is related to location attributes that contain values like "10.98, 12.65" in "lat,long" format. In our data cleaner, we detect that the column contains a separator so we split the column in two, but we do not remove the original column.

However,  my intuition was that we give the location data to CorexText to encode, but currently we do not process them at all. How are we planning to parse location attributes?

**Comment by RqS** [comment]
Spliter will split this column and remove origin column now.
