### ISSUE TITLE
Get the new config file format work with LL0 and LL1 datasets

### ISSUE THREAD

**Issue by serbanstan** [usc-isi-i2/dsbox-ta2#35]
It seems the current config format assumes the existence of TRAIN and TEST directories in the datasets base folder. This makes the schema unusable for the LL0 and LL1 training datasets where the directory structure is different. 

Reverting to the old seed_dataset initialization might be a solution.

**Comment by ckxz105** [comment]
Solved after this commit. 
[https://github.com/usc-isi-i2/dsbox-ta2/commit/3d12bdd1dca95e9318d12edd3f7154cdedfa4860](url)
Now you can leave the "test_data_schema"'s value to be blank or remove this key from config.

In such condition, the system will run "controller.initialize_from_config_train_test" that will split the dataset into 2 parts by functions in Controller.py.

Otherwise, if you speicfic the "test_data_schema" in the system, the system will still load the 2 dataset and run test/train separately.
